rankNames = [
    "Shaman",
    "Pharaoh",
    "Advisor",
    "Senator",
    "High Paladin",
    "Prime Patriarch",
    "Royal Consul",
    "High Minister",
    "Attendant",
    "Prime Chief",
    "Exarch",
    "Chancellor",
    "Alpha Chieftain",
    "Chief",
    "High Duke",
    "Archjusticar",
    "Overlord",
    "Prime Secretary",
    "Regent",
    "Bishop",
    "Demonlord",
    "Prophet",
    "High Justicar",
    "Regent",
    "Prime Sentinel",
    "Knight Commander",
    "Patriarch",
    "Alpha Chieftain",
    "Ensign",
    "High Minister",
    "High King",
    "Archseer",
    "Consul",
    "Minister",
    "King's Advisor",
    "Duke",
    "High Priest",
    "Imperator",
    "Royal Executor",
    "Royal Paladin",
    "Chairman",
    "Royal Spokesman",
    "Beta",
    "Supervisor",
    "High Saint",
    "Prime Templar",
    "Royal Secretary",
    "Royal Vizier",
    "High Magister",
    "Archwarrior",
    "Herald",
    "Royal Paladin",
    "High Seer",
    "Blessed",
    "Archduke",
    "Foreman",
    "Archjusticar",
    "Divine",
    "Ambassador",
    "Lord",
]
